#!/bin/bash

# port defaults
export IMAPPORT=${IMAPPORT:-8143}
export POP3PORT=${POP3PORT:-8110}
export HTTPPORT=${HTTPPORT:-8080}
export LMTPPORT=${LMTPPORT:-8024}
export SIEVEPORT=${SIEVEPORT:-4190}
export WEBPORT=${WEBPORT:-8001}

# start syslog
if [ ! -e '/run/rsyslog.pid' ]; then
  /usr/sbin/rsyslogd
fi

# set up Postfix
if [ "X$RELAYAUTH" != "X" ]; then
  echo "$RELAYHOST $RELAYAUTH" >> /etc/postfix/sasl_passwd
  postmap /etc/postfix/sasl_passwd
fi

perl /srv/testserver/env-replace.pl /srv/testserver/main.cf /etc/postfix/main.cf

/etc/init.d/postfix start

# set up Cyrus
perl /srv/testserver/env-replace.pl /srv/testserver/imapd.conf /etc/imapd.conf
perl /srv/testserver/env-replace.pl /srv/testserver/cyrus.conf /etc/cyrus.conf
rm -f /var/run/cyrus/ready
/usr/cyrus/bin/master -p /var/run/cyrus/master.pid -d -L /var/run/cyrus/log

# wait for Cyrus master to signal readiness
for i in $(seq 1 60); do
  [ -f /var/run/cyrus/ready ] && break
  sleep 1
done

# create users
if [ "X$SKIP_CREATE_USERS" == "X" ]; then
  perl /srv/testserver/make5.pl
fi

# run the webserver
perl /srv/testserver/webserver.pl prefork -l http://*:${WEBPORT}
